version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.17.2
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ALLOW_ORIGIN: '*'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:5

  # Optional: Weaviate Console for easier UI access
  weaviate-console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "8081:80"
    environment:
      WEAVIATE_URL: 'http://weaviate:8080'
    depends_on:
      - weaviate

volumes:
  weaviate_data:
    driver: local
